locale: "tr_TR"

prefix: "&3XTuccar &7Â» "

database:
  #types: MYSQL, SQLITE
  type: SQLITE
  host: localhost
  port: 3306
  username: user
  password: supersecretpass
  tableName: xtuccar

subcommands:
  sell: "sell"
  addStock: "addStock"
  change-price: "changePrice"
  reload: "reload"
  saveAll: "saveAll"